name: Test
on: [ push, pull_request ]

jobs:
    test:
        name: Test with Node v${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 14, 16 ]

        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v2
                with:
                    persist-credentials: false

            -   name: Setup 🔧
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install ♻
                run: npm install

            -   name: Test ✅
                run: npm run test
